//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by 3Dme.rc
//
#define IDR_MANIFEST                    1
#define IDC_APPLY                       4
#define IDS_ABOUTBOX                    101
#define IDD_EMAIL_DIALOG                102
#define MENU_VIEW_MAILS                 102
#define MENU_EXIT                       103
#define MENU_SNAP_TO_DESKTOP_EDGES      104
#define MENU_PREFERENCES                105
#define MENU_STAY_ON_TOP                106
#define MENU_DISABLE_KEY_BLINKING       107
#define MENU_DISABLE_TRAY_BLINKING      108
#define MENU_DISABLE_APP_POPUPS         109
#define MENU_DISABLE_ALARMS             110
#define MENU_DISABLE_REMINDERS          111
#define MENU_DISABLE_CHECKING           112
#define MENU_SHOW_NEW                   113
#define MENU_ABOUT                      114
#define MENU_MARK_READ                  115
#define MENU_MARK_ALL_READ              116
#define MENU_HIDE                       117
#define MENU_CHECK_NOW                  118
#define MAILTHREAD_TIMER                119
#define MENU_DISABLE_ALARM_RUNS         120
#define EMAILMENU_DELETE                121
#define EMAILMENU_PREVIEW               122
#define MENU_SHOW_TIP                   123
#define IDR_BLANK_MENU                  124
#define MENU3D_LOAD_OBJECT              125
#define MENU3D_LOAD_MATERIAL            126
#define MENU3D_CLOSE                    127
#define IDR_MAINFRAME                   128
#define MENU3D_SIZE_HALF                128
#define MENU3D_SIZE_1                   129
#define MENU3D_SIZE_2                   130
#define MENU_DISABLE_REMINDER_RUNS      131
#define MENU_HELP                       132
#define MENU_SHOW_3D                    133
#define MENU3D_SCLICK_CLOSE             134
#define MENU3D_DCLICK_CLOSE             135
#define THREETHREAD_TERMINATE           136
#define MENU_STOP_PENDING_DELETES       137
#define IDI_X                           138
#define MENU_DISABLE_3D_POPUPS          138
#define MENU_CHECK_UPDATES              139
#define EMAILMENU_ALARM_RUNS            140
#define EMAILMENU_REMINDER_RUNS         141
#define EMAILMENU_EMAIL_CLIENT          142
#define MENU3D_EMAIL_CLIENT             143
#define MENU3D_SCLICK_EMAIL_CLIENT      144
#define MENU3D_DCLICK_EMAIL_CLIENT      145
#define MENU3D_STAY_ON_TOP              146
#define MENU_RUN_EMAIL_CLIENT           147
#define HTMLTHREAD_OPEN                 147
#define IDD_APP_PREFS                   148
#define HTMLTHREAD_TERMINATE            148
#define IDI_SOUND                       149
#define DOWNLOADTHREAD_TIMER            149
#define MENU3D_HELP                     150
#define DOWNLOADTHREAD_TERMINATE        150
#define MENU3D_ROTATE_ALWAYS            151
#define MENU_ABOUT_CLIENT               152
#define MENU_ENTER_REGISTRATION_CODE    153
#define MENU3D_SOFTEN_EDGES             154
#define IDB_BIG_CHECK                   155
#define MENU3D_CHANGE_VIEW              155
#define IDB_BIG_X                       156
#define IDI_CHECK                       157
#define EMAILMENU_AUTODELETE_SENDER     158
#define EMAILMENU_AUTODELETE_SUBJECT    159
#define IDR_FS3DME                      161
#define IDR_SCRIPTSKIN                  162
#define IDI_BLANK                       169
#define IDD_PREVIEW_DIALOG              170
#define IDD_STARTUP_TIPS                171
#define IDD_EGG                         176
#define IDB_EGG                         178
#define IDC_HAND_CURSOR                 179
#define IDD_3D                          180
#define IDD_REG                         181
#define IDD_VERSION_CHECKER             182
#define IDD_RUN_DIALOG                  183
#define IDD_DOWNLOAD                    184
#define IDD_SCRIPT_NOTICE               185
#define IDI_TRAY                        187
#define IDD_REG_DOWNLOAD                188
#define IDB_BACK                        196
#define IDB_FORWARD                     197
#define IDB_STOP                        199
#define IDB_REFRESH                     200
#define IDB_HOME                        201
#define IDI_INSTALL                     202
#define IDD_PREFERENCESUI               210
#define IDD_TEST_PREFLET                211
#define IDD_PREFLET_GLOBAL              214
#define IDB_PREFLET_GLOBAL              215
#define IDD_PREFLET_WINDOW              216
#define IDB_PREFLET_WINDOW              217
#define IDD_PREFLET_ABOUT               218
#define IDB_PREFLET_ABOUT               219
#define IDB_PREFLET_CREDITS             220
#define IDB_PREFLET_SUPPORT             221
#define IDD_PREFLET_CREDITS             222
#define IDD_PREFLET_SUPPORT             223
#define IDB_PREFLET_NETWORK             224
#define IDD_PREFLET_NETWORK             225
#define IDD_PREFLET_PROXY               226
#define IDB_PREFLET_PROXY               227
#define IDD_PREFLET_EMAIL_SETTINGS      228
#define IDB_PREFLET_EMAIL_SETTINGS      229
#define IDB_PREFLET_EMAIL_ACCOUNT       230
#define IDD_PREFLET_EMAIL_ACCOUNT       231
#define IDD_PREFLET_ALARM               232
#define IDB_PREFLET_ALARM               233
#define IDB_PREFLET_REMINDER            234
#define IDD_PREFLET_REMINDER            235
#define IDD_PREFLET_SKINS               236
#define IDB_PREFLET_SKINS               237
#define IDC_EMAIL_LIST                  1000
#define IDC_EXIT                        1006
#define IDC_STOP_PENDING_DELETES        1007
#define IDC_CHECK_NOW                   1008
#define IDC_DROP_MENU                   1009
#define IDC_HELP_BUTTON                 1010
#define IDC_PROGRAM_FILE                1023
#define IDC_PROGRAM_BROWSE              1024
#define IDC_PROGRAM_ARG                 1026
#define IDC_EDIT_URL                    1027
#define IDC_NEW_ACCOUNT                 1040
#define IDC_EDIT_ACCOUNT                1041
#define IDC_DELETE_ACCOUNT              1042
#define IDC_STATIC_PROGRAM2             1047
#define IDC_RUN_ON_STARTUP              1049
#define IDC_SELECT_ACCOUNT              1050
#define IDC_TIPS_ON_STARTUP             1051
#define IDC_RUN_PROGRAM                 1051
#define IDC_SHOW_TIPS                   1057
#define IDC_SNAP_TO_DESKTOP_EDGES       1058
#define IDC_STAY_ON_TOP                 1059
#define IDC_NEXT_TIP                    1060
#define IDC_SNAP_TO_EDGES_CHECK         1060
#define IDC_DELETE                      1062
#define IDC_CLOSE                       1063
#define IDC_ABOUT                       1065
#define IDC_MARK_READ                   1066
#define IDC_SHOW_TIP                    1067
#define IDC_SHOW_NEW                    1068
#define IDC_DISABLE_KEY_BLINKING        1069
#define IDC_DISABLE_APP_POPUPS          1070
#define IDC_DISABLE_ALARMS              1071
#define IDC_DISABLE_REMINDERS           1072
#define IDC_DISABLE_CHECKING            1073
#define IDC_SELECT_SKIN                 1074
#define IDC_DISABLE_3D_POPUPS           1075
#define IDC_DISABLE_TRAY_BLINKING       1076
#define IDC_DISABLE_ALARM_RUNS          1077
#define IDC_DISABLE_REMINDER_RUNS       1078
#define IDC_GO_TO_WEBSITE               1079
#define IDC_NO_SKIN_TEXT                1082
#define IDC_SHOW_3D                     1083
#define IDC_REG_CODE                    1084
#define IDC_RUN_EMAIL_CLIENT            1085
#define IDC_DOWNLOAD                    1104
#define IDC_UPDATE_STATUS               1105
#define IDC_UPDATE_TEXT                 1106
#define IDC_PROGRAM_DIR                 1107
#define IDC_CHECK_BETA                  1108
#define IDC_STATIC_PROGRAM1             1110
#define IDC_START_URL                   1111
#define IDC_START_EMAIL                 1112
#define IDC_STATIC_PROGRAM3             1113
#define IDC_STATIC_PROGRAM4             1114
#define IDC_TEST_CONFIG                 1115
#define IDC_OVERALL_PROGRESS            1117
#define IDC_STATIC_SIZE                 1118
#define IDC_STATIC_REMAIN               1119
#define IDC_STATIC_TIME                 1121
#define IDC_STATIC_TIME_LEFT            1122
#define IDC_STATIC_RATE                 1123
#define IDC_STATIC_STATUS               1124
#define IDC_SPEED_SLIDER                1125
#define IDC_MULTIPART_COMBO             1126
#define IDC_STATIC_RATE_AVERAGE         1126
#define IDC_FILE_PROGRESS               1127
#define IDC_SAVE                        1127
#define IDC_STATIC_CURRENT_FILE         1128
#define IDC_DOWNLOAD_URL                1130
#define IDC_VERSION_LIST                1138
#define IDC_REG_DOWNLOAD                1154
#define IDC_REG_WEBSITE                 1155
#define IDC_BROWSER                     1169
#define IDC_BACK                        1170
#define IDC_FORWARD                     1171
#define IDC_STOP                        1172
#define IDC_REFRESH                     1173
#define IDC_HOME                        1174
#define IDC_STATIC_URL                  1175
#define IDC_STATIC_STATUSBAR            1176
#define IDC_WRAP                        1186
#define IDC_LINKIFY                     1187
#define IDC_FROM_EDIT                   1188
#define IDC_REPLYTO_EDIT                1189
#define IDC_DATE_EDIT                   1190
#define IDC_SUBJECT_EDIT                1191
#define IDC_FROM_LABEL                  1192
#define IDC_REPLYTO_LABEL               1193
#define IDC_DATE_LABEL                  1194
#define IDC_SUBJECT_LABEL               1195
#define IDC_MIMEPART_LABEL              1196
#define IDC_TREE                        1204
#define IDC_PREFLET_FRAME               1205
#define IDC_MARK_READ_ON_HIDE_CHECK     1208
#define IDC_AUTO_CHECK_FOR_UPDATES      1209
#define IDC_EDGE_SNAP_DISTANCE_EDIT     1209
#define IDC_ENABLE_TRANSACTION_LOGS     1210
#define IDC_BLINK_KEYBOARD_LED_SPEED    1213
#define IDC_BLINK_TRAY_ICON_SPEED       1214
#define IDC_VERSION_STATIC              1214
#define IDC_REG_STATIC                  1215
#define IDC_CLOSE_3D_POPUP_ON_HIDE_CHECK 1215
#define IDC_HOME_PAGE_STATIC            1216
#define IDC_COMPANY_PAGE_STATIC         1217
#define IDC_HELP_PAGE_STATIC            1218
#define IDC_UPX_PAGE_STATIC             1219
#define IDC_CURL_PAGE_STATIC            1220
#define IDC_GNOME_PAGE_STATIC           1221
#define IDC_DISABLE_AUTODIAL            1222
#define IDC_HTTP_PROXY_CHECK            1225
#define IDC_HTTP_PROXY_HOST_EDIT        1226
#define IDC_HTTP_PROXY_PORT_EDIT        1227
#define IDC_PROXY_HOST_EDIT             1229
#define IDC_PROXY_PORT_EDIT             1230
#define IDC_PROXY_USER_EDIT             1231
#define IDC_PROXY_PASS_EDIT             1232
#define IDC_PROXY_AUTH_CHECK            1233
#define IDC_PROXY_RESOLVE_CHECK         1234
#define IDC_PROXY_TYPE_COMBO            1235
#define IDC_PROXY_HOST_STATIC           1236
#define IDC_PROXY_PORT_STATIC           1237
#define IDC_PROXY_USER_STATIC           1238
#define IDC_PROXY_PASS_STATIC           1239
#define IDC_HTTP_PROXY_HOST_STATIC      1240
#define IDC_HTTP_PROXY_PORT_STATIC      1241
#define IDC_EMAIL_CONFIRM_DELETE_CHECK  1242
#define IDC_ACCOUNT_CREATE_BUTTON       1243
#define IDC_ACCOUNT_CREATE_EDIT         1244
#define IDC_ACCOUNT_DELETE_BUTTON       1245
#define IDC_ACCOUNT_DELETE_COMBO        1246
#define IDC_ACCOUNT_TYPE_POP3_RADIO     1247
#define IDC_ACCOUNT_TYPE_WEBMAIL_RADIO  1248
#define IDC_ACCOUNT_HOST_EDIT           1249
#define IDC_ACCOUNT_PORT_EDIT           1250
#define IDC_ACCOUNT_TYPE_DISABLED_RADIO 1251
#define IDC_ACCOUNT_RETRIEVE_ENTIRE_RADIO 1252
#define IDC_ACCOUNT_RETRIEVE_HEADERS_RADIO 1253
#define IDC_ACCOUNT_RETRIEVE_NOTHING_RADIO 1254
#define IDC_ACCOUNT_SCRIPT_COMBO        1255
#define IDC_ACCOUNT_USERNAME_EDIT       1256
#define IDC_ACCOUNT_PASSWORD_EDIT       1257
#define IDC_ACCOUNT_CHECK_FREQ_EDIT     1258
#define IDC_ACCOUNT_CHECK_FREQ_COMBO    1259
#define IDC_ACCOUNT_SERVER_TIMEOUT_EDIT 1260
#define IDC_ACCOUNT_USE_COLOR_CHECK     1261
#define IDC_ACCOUNT_HOST_STATIC         1262
#define IDC_ACCOUNT_PORT_STATIC         1263
#define IDC_ACCOUNT_SCRIPT_STATIC       1264
#define IDC_ACCOUNT_COLOR_FRAME         1265
#define IDC_ACCOUNT_USERNAME_STATIC     1266
#define IDC_ACCOUNT_PASSWORD_STATIC     1267
#define IDC_ACCOUNT_CHECK_FREQ_STATIC   1268
#define IDC_ACCOUNT_SERVER_TIMEOUT_STATIC 1269
#define IDC_ACCOUNT_SERVER_TIMEOUT_STATIC2 1270
#define IDC_SEPARATOR1_STATIC           1271
#define IDC_SEPARATOR2_STATIC           1272
#define IDC_ALARM_SHOW_3D_CHECK         1273
#define IDC_ALARM_SHOW_WINDOW_CHECK     1274
#define IDC_ALARM_PLAY_SOUND_CHECK      1275
#define IDC_ALARM_SOUND_FILE_EDIT       1276
#define IDC_ALARM_BROWSE_SOUND_BUTTON   1277
#define IDC_ALARM_PLAY_SOUND_BUTTON     1278
#define IDC_ALARM_RUN_EMAIL_CLIENT_CHECK 1279
#define IDC_REMINDER_PLAY_SOUND_CHECK   1279
#define IDC_ALARM_VISIT_WEB_PAGE_CHECK  1280
#define IDC_ALARM_WEB_PAGE_EDIT         1281
#define IDC_ALARM_RUN_PROGRAM_CHECK     1282
#define IDC_ALARM_PROGRAM_EDIT          1283
#define IDC_ALARM_BROWSE_PROGRAM_BUTTON 1284
#define IDC_REMINDER_SOUND_FILE_EDIT    1285
#define IDC_REMINDER_BROWSE_SOUND_BUTTON 1286
#define IDC_REMINDER_PLAY_SOUND_BUTTON  1287
#define IDC_REMINDER_VISIT_WEB_PAGE_CHECK 1288
#define IDC_REMINDER_WEB_PAGE_EDIT      1289
#define IDC_REMINDER_RUN_PROGRAM_CHECK  1290
#define IDC_REMINDER_PROGRAM_EDIT       1291
#define IDC_REMINDER_BROWSE_PROGRAM_BUTTON 1292
#define IDC_REMINDER_FREQUENCY_EDIT     1293
#define IDC_REMINDER_FREQUENCY_COMBO    1294
#define IDC_START_MINIMIZED_CHECK       1297
#define IDC_SHOW_ON_TASKBAR_CHECK       1298
#define IDC_STAY_ON_TOP_CHECK           1299
#define IDC_EDGE_SNAP_DISTANCE_STATIC   1300
#define IDC_ALARM_PROGRAM_ICON          1301
#define IDC_REMINDER_PROGRAM_ICON       1302
#define IDC_SKIN_LIST                   1303
#define IDC_SKIN_NAME_EDIT              1304
#define IDC_SKIN_AUTHOR_EDIT            1305
#define IDC_SKIN_DESCRIPTION_EDIT       1306
#define IDC_SKIN_AUTHOR_URL_EDIT        1307
#define IDC_SKIN_COPYRIGHT_EDIT         1308
#define IDC_MORE_SKINS_LINK             1309
#define IDC_SKIN_THUMB_FRAME            1310
#define TRAY_MESSAGE                    10001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        238
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1311
#define _APS_NEXT_SYMED_VALUE           163
#endif
#endif
